apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namespace: solomon

labels:
- pairs:
    environment: prod
    tier: prod
  includeSelectors: true

configMapGenerator:
  - name: auth-generated-config
    behavior: merge
    literals:
      - GOTRUE_LOG_LEVEL=info
      - DB_NAME=postgres_auth
      - API_EXTERNAL_URL=https://solomon-auth.com/
      - GOTRUE_SITE_URL=https://solomon-auth.com/
      - GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=https://solomon-auth.com/auth/callback
      - GOTRUE_URI_ALLOW_LIST=http://localhost:5173/*,https://to-be-added-real-domain-9889.com/*


