version: "3.9"
services:
  auth:
    container_name: auth
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dev
    ports:
      - '9999:9999'
      - '9100:9100'
    environment:
      - GOTRUE_DB_MIGRATIONS_PATH=/go/src/github.com/supabase/auth/migrations
    restart: always
    volumes:
      - ./:/go/src/github.com/supabase/auth
    command: CompileDaemon --build="make build" --directory=/go/src/github.com/supabase/auth --recursive=true -pattern="(.+\.go|.+\.env)" -exclude=auth -exclude=auth-arm64 -exclude=.env --command="/go/src/github.com/supabase/auth/auth -c=.env.docker"
  postgres:
    env_file: .env
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.postgres.dev
    container_name: auth_postgres
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - auth_data:/var/lib/postgresql/data
    restart: always

  liquibase:
    env_file: .env
    image: liquibase/liquibase
    depends_on:
      - auth
    volumes:
      - ./liquibase_migrations:/liquibase/changelog
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      LIQUIBASE_COMMAND_USERNAME: ${AUTH_DB_ADMIN}
      LIQUIBASE_COMMAND_PASSWORD: ${AUTH_DB_ADMIN_PASSWORD}
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
    command: sh -c "sleep 40 && sh /liquibase/changelog/liquibase_migrations.sh"

volumes:
  auth_data:
