apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: auth-frontend-config
  namespace: auth
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
